<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIVBROR" failures="0" tests="1" name="Default test" time="0.089" errors="0" timestamp="2024-01-28T19:06:54 IST">
  <testcase classname="genericUtility.BaseClass" name="@BeforeSuite bsConfig" time="1.535">
    <failure type="java.sql.SQLException" message="Access denied for user &amp;apos;jdbc:mysql://localhost:3306/vtiger2&amp;apos;@&amp;apos;localhost&amp;apos; (using password: YES)">
      <![CDATA[java.sql.SQLException: Access denied for user 'jdbc:mysql://localhost:3306/vtiger2'@'localhost' (using password: YES)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at genericUtility.BaseClass.bsConfig(BaseClass.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite bsConfig -->
  <testcase classname="genericUtility.BaseClass" name="@BeforeClass bcConfig" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeClass bcConfig -->
  <testcase classname="genericUtility.BaseClass" name="@BeforeMethod bmConfig" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod bmConfig -->
  <testcase classname="genericUtility.BaseClass" name="@AfterMethod amConfig" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod amConfig -->
  <testcase classname="genericUtility.BaseClass" name="@AfterClass acConfig" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass acConfig -->
  <testcase classname="leads_Module.ToCreateALeadTest" name="toCreateALeadAndVerifyTheLeadDetails" time="0.0">
    <skipped/>
  </testcase> <!-- toCreateALeadAndVerifyTheLeadDetails -->
</testsuite> <!-- Default test -->
